- name: Prepare Terraform variables
  hosts: localhost
  tasks:
    - name: Decrypt secrets
      ansible.builtin.include_vars:
        file: secrets.yml
        name: secrets
        vault_password_file: vault_pass.txt

    - name: Export secrets to environment variables
      ansible.builtin.set_fact:
        TF_VAR_yc_token: "{{ secrets.yc_token }}"
        TF_VAR_cloud_id: "{{ secrets.cloud_id }}"
        TF_VAR_folder_id: "{{ secrets.folder_id }}"
